export let teams = [
  {
    id: 1,
    name: 'Qatar',
    flag: 'https://www.worldometers.info/img/flags/small/tn_qa-flag.gif',
    group: 'A',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 2,
    name: 'Equador',
    flag: 'https://www.worldometers.info/img/flags/small/tn_ec-flag.gif',
    group: 'A',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 3,
    name: 'Senegal',
    flag: 'https://www.worldometers.info/img/flags/small/tn_sg-flag.gif',
    group: 'A',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 4,
    name: 'Holanda',
    flag: 'https://www.worldometers.info/img/flags/small/tn_nl-flag.gif',
    group: 'A',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 5,
    name: 'Inglaterra',
    flag: 'https://www.worldometers.info/img/flags/uk-flag.gif',
    group: 'B',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 6,
    name: 'Irã',
    flag: 'https://www.worldometers.info/img/flags/small/tn_ir-flag.gif',
    group: 'B',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 7,
    name: 'Estados Unidos',
    flag: 'https://www.worldometers.info/img/flags/small/tn_us-flag.gif',
    group: 'B',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 8,
    name: 'Gales',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Flag_of_Wales.svg/188px-Flag_of_Wales.svg.png',
    group: 'B',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 9,
    name: 'Argentina',
    flag: 'https://www.worldometers.info/img/flags/small/tn_ar-flag.gif',
    group: 'C',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 10,
    name: 'Arábia Saudita',
    flag: 'https://www.worldometers.info/img/flags/small/tn_sa-flag.gif',
    group: 'C',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 11,
    name: 'México',
    flag: 'https://www.worldometers.info/img/flags/small/tn_mx-flag.gif',
    group: 'C',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: 'Polônia',
    flag: 'https://www.worldometers.info/img/flags/small/tn_pl-flag.gif',
    group: 'C',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 13,
    name: 'França',
    flag: 'https://www.worldometers.info/img/flags/small/tn_fr-flag.gif',
    group: 'D',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 14,
    name: 'Austrália',
    flag: 'https://www.worldometers.info/img/flags/small/tn_as-flag.gif',
    group: 'D',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 15,
    name: 'Dinamarca',
    flag: 'https://www.worldometers.info/img/flags/small/tn_da-flag.gif',
    group: 'D',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 16,
    name: 'Tunísia',
    flag: 'https://www.worldometers.info/img/flags/small/tn_ts-flag.gif',
    group: 'D',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 17,
    name: 'Espanha',
    flag: 'https://www.worldometers.info/img/flags/small/tn_sp-flag.gif',
    group: 'E',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 18,
    name: 'Costa Rica',
    flag: 'https://www.worldometers.info/img/flags/small/tn_cs-flag.gif',
    group: 'E',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 19,
    name: 'Alemanha',
    flag: 'https://www.worldometers.info/img/flags/small/tn_gm-flag.gif',
    group: 'E',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 20,
    name: 'Japão',
    flag: 'https://www.worldometers.info/img/flags/small/tn_ja-flag.gif',
    group: 'E',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 21,
    name: 'Bélgica',
    flag: 'https://www.worldometers.info/img/flags/small/tn_be-flag.gif',
    group: 'F',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 22,
    name: 'Canadá',
    flag: 'https://www.worldometers.info/img/flags/small/tn_ca-flag.gif',
    group: 'F',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 23,
    name: 'Marrocos',
    flag: 'https://www.worldometers.info/img/flags/small/tn_mo-flag.gif',
    group: 'F',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 24,
    name: 'Croácia',
    flag: 'https://www.worldometers.info/img/flags/small/tn_hr-flag.gif',
    group: 'F',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 25,
    name: 'Brasil',
    flag: 'https://www.worldometers.info/img/flags/small/tn_br-flag.gif',
    group: 'G',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 26,
    name: 'Sérvia',
    flag: 'https://www.worldometers.info/img/flags/small/tn_ri-flag.gif',
    group: 'G',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 27,
    name: 'Suíça',
    flag: 'https://www.worldometers.info/img/flags/small/tn_sz-flag.gif',
    group: 'G',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 28,
    name: 'Camarôes',
    flag: 'https://www.worldometers.info/img/flags/small/tn_cm-flag.gif',
    group: 'G',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 29,
    name: 'Portugal',
    flag: 'https://www.worldometers.info/img/flags/small/tn_po-flag.gif',
    group: 'H',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 30,
    name: 'Gana',
    flag: 'https://www.worldometers.info/img/flags/small/tn_gh-flag.gif',
    group: 'H',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 31,
    name: 'Uruguai',
    flag: 'https://www.worldometers.info/img/flags/small/tn_uy-flag.gif',
    group: 'H',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 32,
    name: 'Coreia do Sul',
    flag: 'https://www.worldometers.info/img/flags/small/tn_ks-flag.gif',
    group: 'H',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
];


export default class squads {
  constructor(name, flag, grupo) {
    this.name = 'Holanda',
    this.flag = 'Hplanda Flag'
    this.grupo = 'A'
  }
}