const teams = [
  {
    id: 1,
    name: 'Qatar',
    flag: 'https://www.worldometers.info/img/flags/small/tn_qa-flag.gif',
    group: 'A',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 2,
    name: 'Equador',
    flag: 'https://www.worldometers.info/img/flags/small/tn_ec-flag.gif',
    group: 'A',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 3,
    name: 'Senegal',
    flag: 'https://www.worldometers.info/img/flags/small/tn_sg-flag.gif',
    group: 'A',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 4,
    name: 'Holanda',
    flag: 'https://www.worldometers.info/img/flags/small/tn_nl-flag.gif',
    group: 'A',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 5,
    name: 'Inglaterra',
    flag: 'https://www.worldometers.info/img/flags/uk-flag.gif',
    group: 'B',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 6,
    name: 'Irã',
    flag: 'https://www.worldometers.info/img/flags/small/tn_ir-flag.gif',
    group: 'B',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 7,
    name: 'Estados Unidos',
    flag: 'https://www.worldometers.info/img/flags/small/tn_us-flag.gif',
    group: 'B',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 8,
    name: 'Gales',
    flag: 'https://upload.wikimedia.org/wikipedia/commons/thumb/d/dc/Flag_of_Wales.svg/188px-Flag_of_Wales.svg.png',
    group: 'B',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 9,
    name: 'Argentina',
    flag: 'https://www.worldometers.info/img/flags/small/tn_ar-flag.gif',
    group: 'C',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 10,
    name: 'Arábia Saudita',
    flag: 'https://www.worldometers.info/img/flags/small/tn_sa-flag.gif',
    group: 'C',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 11,
    name: 'México',
    flag: 'https://www.worldometers.info/img/flags/small/tn_mx-flag.gif',
    group: 'C',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
  {
    id: 12,
    name: '',
    flag: '',
    group: '',
    points: 0,
    gp: 0,
    gc: 0,
    sg: 0,
    classification: null,
    pj: 0,
    wins: 0,
    lost: 0,
    tie: 0,
  },
]